// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYmOfs-6VxH3BIPRDjzhCqiF-vKrFLnYk',
    appId: '1:635669134252:web:974d57c86bcc50395dd809',
    messagingSenderId: '635669134252',
    projectId: 'moawen-3e790',
    authDomain: 'moawen-3e790.firebaseapp.com',
    databaseURL: 'https://moawen-3e790-default-rtdb.firebaseio.com',
    storageBucket: 'moawen-3e790.appspot.com',
    measurementId: 'G-L6M3WH72QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2kkoHPwZa0WEyPLpltxGd5NRXkyEW3CM',
    appId: '1:635669134252:android:7534a03d688409825dd809',
    messagingSenderId: '635669134252',
    projectId: 'moawen-3e790',
    databaseURL: 'https://moawen-3e790-default-rtdb.firebaseio.com',
    storageBucket: 'moawen-3e790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8BIryqS19C5ikh-VdS_Oh2K9wAOGiahU',
    appId: '1:635669134252:ios:534173cc2757bd1a5dd809',
    messagingSenderId: '635669134252',
    projectId: 'moawen-3e790',
    databaseURL: 'https://moawen-3e790-default-rtdb.firebaseio.com',
    storageBucket: 'moawen-3e790.appspot.com',
    iosClientId:
        '635669134252-arreskcpkq70o9i9v7071eg2h05bfeig.apps.googleusercontent.com',
    iosBundleId: 'com.example.moawen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8BIryqS19C5ikh-VdS_Oh2K9wAOGiahU',
    appId: '1:635669134252:ios:534173cc2757bd1a5dd809',
    messagingSenderId: '635669134252',
    projectId: 'moawen-3e790',
    databaseURL: 'https://moawen-3e790-default-rtdb.firebaseio.com',
    storageBucket: 'moawen-3e790.appspot.com',
    iosClientId:
        '635669134252-arreskcpkq70o9i9v7071eg2h05bfeig.apps.googleusercontent.com',
    iosBundleId: 'com.example.moawen',
  );
}
